### PR TITLE
Updated card list, images, and created new Python replacement for Perl Script

### PR DESCRIPTION
**Pull request by Ryan-Myers**
Ok, so I wanted to get the list of cards and images updated for the site. Unfortunately I was kind of picky about formatting, it I couldn't get the Perl script card_update.pl to convert the unicode characters properly, so instead I rewrote the script in Python where I was able to do it.

Included in this pull request is the new list of cards from NRDB, the images that go along with them, and the new Python script.

One thing I didn't do with the new cards,json file was run the Reddit COTD routine since I didn't feel like setting up a Ruby environment for it. Feel free to update it using that script if still desired.

### CODE REVIEW

**Comment by shyndman** [comment]
Hey Ryan,

I'd prefer if you at least left behind the existing COTD metadata, rather than overwrite.

**Comment by Ryan-Myers** [comment]
Fair enough. I wasn't sure how easy it was to just run the script to add them yourself, but I've now gone in and installed Ruby and ran it myself. I can see that there was some manual effort involved, so I've now updated this pull request with the Reddit COTD links. I've got a copy of it running on my server if you'd like to check it out. http://foldor.mynetgear.com

**Comment by shyndman** [comment]
Looks awesome! Thanks for the update.

I'm going to do an image optimization run, then I'll push this live.

**Comment by shyndman** [comment]
Knocked off a few meg.

It's now pushed live. Thanks again.

**Pull request merged**
